version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - saas-network

  db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: saas_microservices
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    networks:
      - saas-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - saas-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - saas-network

  api-gateway: # API Gateway
    build:
      context: .
      args:
        APP_NAME: api-gateway
    ports:
      - '3000:3000'
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    depends_on:
      - rabbitmq
      - db
      - auth-service
      - user-service
      - apikey-service
      - audit-log
      - payment-service
      - file-service
      - notification-service
      - setting-service
      - search-service
      - backgroundjob-service
    networks:
      - saas-network

  auth-service:
    build:
      context: .
      args:
        APP_NAME: auth-service
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/auth_db?schema=public
      - RP_ID=localhost
      - EXPECTED_ORIGIN=http://localhost:3000
      - JWT_SECRET=supersecret
      - ENCRYPTION_KEY=0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef
    depends_on:
      - rabbitmq
      - db
    networks:
      - saas-network

  user-service:
    build:
      context: .
      args:
        APP_NAME: user-service
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/user_db?schema=public
    depends_on:
      - rabbitmq
      - db
    networks:
      - saas-network

  apikey-service:
    build:
      context: .
      args:
        APP_NAME: apikey-service
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/apikey_db?schema=public
    depends_on:
      - rabbitmq
      - db
    networks:
      - saas-network

  audit-log:
    build:
      context: .
      args:
        APP_NAME: audit-log
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/audit_log_db?schema=public
    depends_on:
      - rabbitmq
      - db
    networks:
      - saas-network

  payment-service:
    build:
      context: .
      args:
        APP_NAME: payment-service
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/payment_db?schema=public
    depends_on:
      - rabbitmq
      - db
    networks:
      - saas-network

  file-service:
    build:
      context: .
      args:
        APP_NAME: file-service
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/file_db?schema=public
    depends_on:
      - rabbitmq
      - db
    networks:
      - saas-network

  notification-service:
    build:
      context: .
      args:
        APP_NAME: notification-service
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/notification_db?schema=public
    depends_on:
      - rabbitmq
      - db
    networks:
      - saas-network

  setting-service:
    build:
      context: .
      args:
        APP_NAME: setting-service
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/setting_db?schema=public
    depends_on:
      - rabbitmq
      - db
    networks:
      - saas-network

  search-service:
    build:
      context: .
      args:
        APP_NAME: search-service
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/search_db?schema=public
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - rabbitmq
      - db
      - elasticsearch
    networks:
      - saas-network

  backgroundjob-service:
    build:
      context: .
      args:
        APP_NAME: backgroundjob-service
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/backgroundjob_db?schema=public
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - rabbitmq
      - db
      - redis
    networks:
      - saas-network

networks:
  saas-network:
    driver: bridge

volumes:
  postgres_data:
  elasticsearch_data:
  redis_data:
