version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - saas-network

  db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: saas_microservices
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    networks:
      - saas-network

  api-gateway: # API Gateway
    build:
      context: .
      args:
        APP_NAME: api-gateway
    ports:
      - '3000:3000'
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    depends_on:
      - rabbitmq
      - db
      - auth-service
      - user-service
      - apikey-service
      - logger-service
      - payment-service
      - file-service
      - notification-service
    networks:
      - saas-network

  auth-service:
    build:
      context: .
      args:
        APP_NAME: auth-service
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/auth_db?schema=public
      - RP_ID=localhost
      - EXPECTED_ORIGIN=http://localhost:3000
      - JWT_SECRET=supersecret
      - ENCRYPTION_KEY=0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef
    depends_on:
      - rabbitmq
      - db
    networks:
      - saas-network

  user-service:
    build:
      context: .
      args:
        APP_NAME: user-service
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/user_db?schema=public
    depends_on:
      - rabbitmq
      - db
    networks:
      - saas-network

  apikey-service:
    build:
      context: .
      args:
        APP_NAME: apikey-service
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/apikey_db?schema=public
    depends_on:
      - rabbitmq
      - db
    networks:
      - saas-network

  logger-service:
    build:
      context: .
      args:
        APP_NAME: logger-service
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/logger_db?schema=public
    depends_on:
      - rabbitmq
      - db
    networks:
      - saas-network

  payment-service:
    build:
      context: .
      args:
        APP_NAME: payment-service
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/payment_db?schema=public
    depends_on:
      - rabbitmq
      - db
    networks:
      - saas-network

  file-service:
    build:
      context: .
      args:
        APP_NAME: file-service
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/file_db?schema=public
    depends_on:
      - rabbitmq
      - db
    networks:
      - saas-network

  notification-service:
    build:
      context: .
      args:
        APP_NAME: notification-service
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/notification_db?schema=public
    depends_on:
      - rabbitmq
      - db
    networks:
      - saas-network

networks:
  saas-network:
    driver: bridge

volumes:
  postgres_data:
